Сверстан главный экран ленты
Dkrshn/ImageFeed pull request #1
Opened 2023-01-31 19:04 UTC by Dkrshn

- Добавлены 20 картинок
- Добавлена сегодняшняя дата
-  Добавлена кнопка лайка

2023-02-01 17:15 UTC, IBDesignable requested changes
Лейбл заверстан не по макету
<img width="811" alt="Снимок экрана 2023-02-01 в 18 50 55" src="https://user-images.githubusercontent.com/121577115/216114242-404d8878-e545-4030-9be2-49f2728c7a14.png">

2023-02-01 17:15 UTC, IBDesignable commented on ImageFeed/ImageList/ImagesListViewController.swift
>      }
Давай  super.viewDidLoad() поставим в начало. Это хорошая. привычка чтобы не забывать вызывать методы super в методах переопределения. 
К тому же мы не знаем какую работу выполняет на самом деле super.viewDidLoad, поэтому лучше дать системе сделать все необходимое, чтобы вью контроллер отобразился правильно.

2023-02-01 17:15 UTC, IBDesignable commented on ImageFeed/ImageList/ImagesListViewController.swift
> +            return
Хорошая проверка! Хотя я долго искала почему у тебя ломается таблица 
Дело в том, что не все изображения добавлены в проект. Номер 5 пропущен.
<img width="211" alt="Снимок экрана 2023-02-01 в 18 58 57" src="https://user-images.githubusercontent.com/121577115/216113949-d7be8fcb-7ca2-4612-93a9-0c2347ce2618.png"><img width="211" alt="Снимок экрана 2023-02-01 в 18 58 43" src="https://user-images.githubusercontent.com/121577115/216113952-3afa1092-3170-440d-b652-66b57a81cbb4.png"><img width="211" alt="Снимок экрана 2023-02-01 в 18 59 01" src="https://user-images.githubusercontent.com/121577115/216113943-340782e6-e0de-4415-b374-f722563a1da0.png">

2023-02-02 10:19 UTC, Dkrshn commented on ImageFeed/ImageList/ImagesListViewController.swift
>      }
Поправил )

2023-02-02 10:19 UTC, Dkrshn commented on ImageFeed/ImageList/ImagesListViewController.swift
> +            return
Поправил )

2023-02-02 19:52 UTC, IBDesignable approved these changes

2023-02-03 07:42 UTC, merged