Sprint 11
Dkrshn/ImageFeed pull request #6
Opened 2023-03-14 18:53 UTC by Dkrshn

Работа по 11 спринту. 
Единственное, у меня появился баг, не работает сегвей перехода на Webview. Может это только у меня на ПК? Xcode выдает ошибку has no segue with identifier 'ShowWebView'", но у меня есть этот сегвей, более того, я в этом куске кода ничего не менял.

2023-03-15 16:14 UTC, protos17 requested changes

2023-03-15 16:14 UTC, protos17 commented on Helper/NetworkClient.swift
Необходимо применить выравнивание

2023-03-15 16:14 UTC, protos17 commented on Helper/OAuth2TokenStorage.swift
>      private let userDefaults = UserDefaults.standard
Рекомендую удалить userDefaults, больше не понадобится

2023-03-15 16:14 UTC, protos17 commented on Helper/OAuth2TokenStorage.swift
> +//            return record
Рекомендую удалять лишний закомментированный код

2023-03-15 16:14 UTC, protos17 commented on Helper/OAuth2TokenStorage.swift
> +            //userDefaults.set(newValue, forKey: Keys.token.rawValue)
Рекомендую удалить

2023-03-15 16:14 UTC, protos17 commented on Helper/UIBlockingProgressHUD.swift
> +        window?.isUserInteractionEnabled = false
Необходимо заменить на true

2023-03-15 16:14 UTC, protos17 commented on ImageFeed/Auth/OAuth2Service.swift
> +        if task != nil {
Можно не делать проверку, потому что task?.cancel() ничего не выполнит, если task будет nil

2023-03-15 16:14 UTC, protos17 commented on ImageFeed/ImageList/ProfileViewController.swift
>  class ProfileViewController: UIViewController {
Давай проставлять ключевое слово `final` классам для ускорения работы компилятора.
Это нужно для оптимизация работы компилятора: ты явно сообщаешь о том, 
что класс не планируется расширять наследованием. 
В таком случае компилятор будет быстрее находить адрес ячейки памяти при вызове функции.

2023-03-15 16:14 UTC, protos17 commented on ImageFeed/ImageList/ProfileViewController.swift
> +    let logOutButton = UIButton.systemButton(with: UIImage(named: "ipad.and.arrow.forward")!, target: nil, action: nil)
Здесь стоит добавить `private`
Необходимо указывать private  для того, чтобы спрятать детали реализации конкретной части функциональности, 
когда они используются только внутри области объявления.

2023-03-15 16:14 UTC, protos17 commented on ImageFeed/Splash/SplashViewController.swift
> +       self.switchToTabBarController()
Необходимо убрать, чтобы можно было получить аватарку

2023-03-15 16:14 UTC, protos17 commented on ImageFeed/Splash/SplashViewController.swift
>          guard let window = UIApplication.shared.windows.first else { fatalError("Invalid Configuration") }
По своему опыту хотел бы отметить, что в продакшене не используют fatalError, советую заменить на assertionFailure.

2023-03-15 16:14 UTC, protos17 commented on ProfileService/ProfileImageService.swift
> +        if task != nil {
Можно не делать проверку

2023-03-15 16:14 UTC, protos17 commented on ImageFeed/Auth/AuthViewController.swift
>          performSegue(withIdentifier: showWebView, sender: nil)
Здесь необходимо переходить без сегвея:
        if let viewController = UIStoryboard(name: "Main", bundle: .main)
            .instantiateViewController(withIdentifier: "WebViewViewController") as? WebViewViewController {
            viewController.modalPresentationStyle = .fullScreen
            viewController.delegate = self
            present(viewController, animated: true)
        }

2023-03-15 19:12 UTC, Dkrshn commented on Helper/NetworkClient.swift
Проект выравнял )

2023-03-15 19:13 UTC, Dkrshn commented on Helper/OAuth2TokenStorage.swift
>      private let userDefaults = UserDefaults.standard
Удалил

2023-03-15 19:13 UTC, Dkrshn commented on Helper/OAuth2TokenStorage.swift
> +//            return record
Удалил

2023-03-15 19:13 UTC, Dkrshn commented on Helper/OAuth2TokenStorage.swift
> +            //userDefaults.set(newValue, forKey: Keys.token.rawValue)
Удалил

2023-03-15 19:13 UTC, Dkrshn commented on Helper/UIBlockingProgressHUD.swift
> +        window?.isUserInteractionEnabled = false
Заменил

2023-03-15 19:13 UTC, Dkrshn commented on ImageFeed/Auth/OAuth2Service.swift
> +        if task != nil {
Убрал

2023-03-15 19:13 UTC, Dkrshn commented on ImageFeed/ImageList/ProfileViewController.swift
>  class ProfileViewController: UIViewController {
Добавил )

2023-03-15 19:13 UTC, Dkrshn commented on ImageFeed/ImageList/ProfileViewController.swift
> +    let logOutButton = UIButton.systemButton(with: UIImage(named: "ipad.and.arrow.forward")!, target: nil, action: nil)
Да, добавил

2023-03-15 19:13 UTC, Dkrshn commented on ImageFeed/Splash/SplashViewController.swift
> +       self.switchToTabBarController()
Да, верно, поправил

2023-03-15 19:13 UTC, Dkrshn commented on ImageFeed/Splash/SplashViewController.swift
>          guard let window = UIApplication.shared.windows.first else { fatalError("Invalid Configuration") }
Поправил

2023-03-15 19:13 UTC, Dkrshn commented on ProfileService/ProfileImageService.swift
> +        if task != nil {
Убрал

2023-03-15 19:13 UTC, Dkrshn commented on ImageFeed/Auth/AuthViewController.swift
>          performSegue(withIdentifier: showWebView, sender: nil)
Понял ошибку, заменил

2023-03-16 16:50 UTC, protos17 approved these changes

2023-03-17 09:36 UTC, merged